### ISSUE TITLE
I have a problem with DNS change can you help me please?

### ISSUE THREAD

**Issue by IvanDeFelice76** [lcp/NetworkManager#1]
nmcli con mod enp2s0 ipv4.ignore-auto-dns yes
nmcli con mod enp2s0 ipv4.dns "1.1.1.1, 1.0.0.1"
nmcli con mod enp2s0 ipv6.ignore-auto-dns yes
nmcli con mod enp2s0 ipv6.dns "2606:4700:4700::1111 ,2606:4700:4700::1001"

I'm doing something wrong in Fedora 33 and can't set them correctly

**Comment by lcp** [comment]
Although I would like to help, unfortunately, I don't work on NM for more than 7 years. Please ask for help from the Fedora or NetworkManager community.
